name: C++ CI with Make

on:
  push:
    branches: [branchHTTPserver]
  pull_request:
    branches: [branchHTTPserver]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev

      - name: Generate configure script
        run: |
          autoreconf --install

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Run tests
        run: make check

      - name: Upload test log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: test-suite.log

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: List Buildx builders
        run: docker buildx ls

      - name: DockerHub login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for amd64
        run: docker build --platform=linux/amd64 -t mav1z/httpserver:amd64 --push .

      - name: Build Docker image for arm64
        run: docker build --platform=linux/arm64 -t mav1z/httpserver:arm64 --push .

      - name: Create Docker manifest
        run: docker manifest create mav1z/httpserver --amend mav1z/httpserver:amd64 --amend mav1z/httpserver:arm64

      - name: Push Docker manifest
        run: docker manifest push mav1z/httpserver
