name: C++ CI with Make

on:
  push:
    branches: [branchHTTPservMulti]
  pull_request:
    branches: [branchHTTPservMulti]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake g++ libboost-test-dev

      - name: Generate configure script
        run: |
          autoreconf --install
      - name: confg QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: List Buildx builders
        run: docker buildx ls

      - name: DockerHub login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for amd64
        run: docker build --platform=linux/amd64 -t maxv1z/httpserver:amd64 --push .

      - name: Build Docker image for arm64
        run: docker build --platform=linux/arm64 -t maxv1z/httpserver:arm64 --push .

      - name: Create Docker manifest
        run: docker manifest create maxv1z/httpserver --amend maxv1z/httpserver:amd64 --amend maxv1z/httpserver:arm64

      - name: Push Docker manifest
        run: docker manifest push maxv1z/httpserver
